# Site Settings
title: Mae Sliwinski
name: Mae Sliwinski
description: Mae Sliwinski â€“ Projects and CV
url: "https://cornell-mae-ug.github.io/fa25-portfolio-maesliwinski/"
baseurl: "https://cornell-mae-ug.github.io/fa25-portfolio-maesliwinski/"

theme: jekyll-theme-minimal

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Optional styling
color_scheme: light

plugins:
  - jekyll-seo-tag
