# Site Settings
title: Mae Sliwinski
name: Mae Sliwinski
description: Mae Sliwinski â€“ Projects and CV
url: "https://maesliwinski.github.io"
baseurl: ""

theme: jekyll-theme-minimal

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Optional styling
color_scheme: light

plugins:
  - jekyll-seo-tag
